import { useRef, useState } from 'react';
import { MapPin, Pencil, Plus, X, Sparkles } from 'lucide-react';
import type { Photo } from '../types/photo';
import type { TripStop } from '../types/story';
import { manualPlace, presentStop } from '../utils/itineraryPresentation';
import { generateStopCaption } from '../services/captionService';
export function ItineraryStopCard({stop:raw,index,photos,disabled,onUpdate,onRemove,onPhotoChange}:{stop:TripStop;index:number;photos:Photo[];disabled:boolean;onUpdate:(patch:Partial<TripStop>)=>void;onRemove:()=>void;onPhotoChange:(ids:string[])=>void}) {
  const stop=presentStop(raw);
  const pending=useRef(false);const [writing,setWriting]=useState(false),[captionError,setCaptionError]=useState('');
  const writeCaption=async()=>{if(pending.current)return;pending.current=true;setWriting(true);setCaptionError('');try{const selected=stop.representativePhotoIds.slice(0,4).map(id=>photos.find(p=>p.id===id));if(selected.some(p=>!p))throw new Error('Missing photo');const caption=await generateStopCaption({placeName:stop.placeName,startTime:stop.startTime,photos:selected as Photo[]});onUpdate({caption,captionSource:'ai'});}catch{setCaptionError('这次没写出来，再试一次吧。');}finally{pending.current=false;setWriting(false);}};
  const [editing,setEditing]=useState<'time'|'place'|'caption'|null>(null);
  const [addingPhoto,setAddingPhoto]=useState(false);
  const [pendingPhotos,setPendingPhotos]=useState<string[]>([]);
  const source=stop.placeSource;
  const sourceLabel=source==='gps'?'GPS 识别':source==='ai'?'AI 识别 · 请确认':'';
  const finish=()=>setEditing(null);
  return <article className="paper-panel itinerary-stop confirm-stop" aria-label={`第 ${index+1} 站`}>
    <span className="stop-index">{String(index+1).padStart(2,'0')}</span>
    <header className="stop-summary"><div className="stop-time">{editing==='time'?<input autoFocus type="time" aria-label={`第 ${index+1} 站时间`} value={/^\d{2}:\d{2}$/.test(stop.startTime)?stop.startTime:''} onChange={e=>onUpdate({startTime:e.target.value})} onBlur={finish} onKeyDown={e=>{if(e.key==='Enter')finish();}}/>:<button type="button" disabled={disabled} onClick={()=>setEditing('time')} aria-label={`编辑第 ${index+1} 站时间`}>{stop.startTime||'添加时间'}<Pencil size={13}/></button>}</div>
    <div className="stop-place-block"><div className="stop-place">{editing==='place'?<input autoFocus aria-label={`第 ${index+1} 站地点`} placeholder="输入景点、餐厅或区域名称" maxLength={40} value={raw.placeSource==='manual'?raw.placeName:stop.placeName} onChange={e=>onUpdate(manualPlace(e.target.value))} onBlur={()=>{onUpdate(manualPlace((raw.placeSource==='manual'?raw.placeName:stop.placeName).trim()));finish();}} onKeyDown={e=>{if(e.key==='Enter'&&!e.nativeEvent.isComposing)e.currentTarget.blur();}}/>:<button type="button" disabled={disabled} className={!stop.placeName?'add-place':''} onClick={()=>setEditing('place')}>{stop.placeName?<><MapPin size={18}/><span>{stop.placeName}</span><Pencil size={13}/></>:<><span>添加地点</span><Pencil size={13}/></>}</button>}{sourceLabel&&<span className={`place-source source-${source}`}>{sourceLabel}</span>}</div><p className="place-helper">输入景点、餐厅或区域名称</p></div></header>
    <div className="stop-photos">{stop.representativePhotoIds.slice(0,4).map(id=>{const photo=photos.find(p=>p.id===id);return photo?<div className="stop-photo" key={id}><img src={photo.thumbnailUrl} alt={photo.fileName} loading="lazy"/><button type="button" aria-label={`移除 ${photo.fileName}`} disabled={disabled} onClick={()=>onPhotoChange(stop.representativePhotoIds.filter(other=>other!==id))}><X size={14}/></button></div>:null;})}{stop.representativePhotoIds.length<4&&<button type="button" className="add-stop-photo" disabled={disabled} onClick={()=>setAddingPhoto(true)}><Plus size={18}/><span>添加照片</span></button>}</div>
    {addingPhoto&&<div className="photo-picker-modal" role="dialog" aria-label="添加这一站的照片"><div className="photo-picker-card"><h3>添加这一站的照片</h3><p>可连续选择，最多添加 {4-stop.representativePhotoIds.length} 张</p><div className="picker-grid">{photos.filter(p=>!stop.representativePhotoIds.includes(p.id)).map(photo=><button type="button" key={photo.id} className={`picker-photo ${pendingPhotos.includes(photo.id)?'is-picked':''}`} onClick={()=>setPendingPhotos(current=>current.includes(photo.id)?current.filter(id=>id!==photo.id):current.length<4-stop.representativePhotoIds.length?[...current,photo.id]:current)}><img src={photo.thumbnailUrl} alt={photo.fileName}/></button>)}</div><div className="picker-actions"><span>已选 {pendingPhotos.length} / {4-stop.representativePhotoIds.length}</span><button type="button" className="secondary-button" onClick={()=>{setAddingPhoto(false);setPendingPhotos([]);}}>取消</button><button type="button" className="primary-button" disabled={!pendingPhotos.length} onClick={()=>{onPhotoChange([...stop.representativePhotoIds,...pendingPhotos]);setAddingPhoto(false);setPendingPhotos([]);}}>添加所选照片</button></div></div></div>}
    <section className="stop-caption"><div className="caption-heading"><span>旅行配文</span><span className="caption-actions"><button type="button" disabled={disabled||writing} onClick={writeCaption}><Sparkles size={13}/>{writing?'正在看照片…':'AI 帮你写'}</button></span></div>
      {editing==='caption'?<textarea autoFocus aria-label={`第 ${index+1} 站旅行配文`} value={raw.caption} disabled={writing} maxLength={80} placeholder="写下一句关于这一站的旅行记录" onChange={e=>onUpdate({caption:e.target.value,captionSource:'manual'})} onBlur={finish} onKeyDown={e=>{if((e.ctrlKey||e.metaKey)&&e.key==='Enter')finish();}}/>:<button type="button" className={`caption-copy${stop.caption?'':' caption-pending'}`} disabled={disabled} onClick={()=>setEditing('caption')}>{stop.caption||'写下一句关于这一站的旅行记录'}</button>}
      {captionError&&<p role="alert">{captionError}</p>}
    </section>
    <button type="button" className="remove-stop" disabled={disabled} onClick={onRemove}>移除这一站</button>
  </article>;
}
